### PR TITLE
Improved Test Coverage & Add Support for Travis CI and CodeCoverage

### PR DESCRIPTION
**Pull request by droidchef**
- Added a few more tests
- Added Jacoco Support and Integrated Travis CI
- Added Travis CI badge to README.md
- Added missing Gradle-Wrapper.jar
- Added Code Coverage badge to README.md 
- Now shows Test Coverage of the code.

You'll have to do two changes when after you merge:
1. Activate Travis CI for this repo. [https://travis-ci.org](Click Here) 
2. Activate CodeCoverage for this repo. [https://codecov.io](Click Here)
3. Change the links in the README.md file 
   from 

```
[![Travis](https://img.shields.io/travis/ishan1604/yadi.svg)](https://travis-ci.org/ishan1604/yadi) [![Code Coverage](https://img.shields.io/codecov/c/github/ishan1604/yadi.svg)](https://codecov.io/github/ishan1604/yadi)
```

to

```
[![Travis](https://img.shields.io/travis/curioustechizen/yadi.svg)](https://travis-ci.org/curioustechizen/yadi) [![Code Coverage](https://img.shields.io/codecov/c/github/curioustechizen/yadi.svg)](https://codecov.io/github/curioustechizen/yadi)
```

### CODE REVIEW

**Comment by curioustechizen** [comment]
@ishan1604 thanks for this PR. I will probably merge it during the weekend. And +1 to the power of open source - a library that I hardly expected anyone to use already sees a PR that adds a lot of value to the lib :-)

**Comment by ishan1604** [comment]
@curioustechizen I moved to Amsterdam! Do you want to catch up sometime ? 😄

**Comment by curioustechizen** [comment]
@ishan1604 for sure. Do I contact you on the apache email id that is on your GitHub profile?
(And who knew one could use GitHub issues as a chat service :D )

**Comment by ishan1604** [comment]
Sure that works! :) looking forward to hear from you.

**Pull request merged**
